# Use an official Node runtime as a parent image
FROM node:20 AS peapodos

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install --network-timeout 100000

# Copy the rest of your app's source code
COPY . .

# Your app binds to port 3000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 3000

# Define the command to run your app using CMD which defines your runtime
# CMD ["yarn", "dev"] # Must be done from the CLI to allow for user input
CMD ["/bin/bash"]