# Use an official Node runtime as a parent image
FROM node:20 AS peapodos-local

# Set the working directory in the container
WORKDIR /usr/src/app

# Install apt dependencies
RUN apt-get update && apt-get install -y udev

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install --frozen-lockfile --non-interactive --network-timeout 100000

# Copy the rest of your app's source code
COPY . .

# Your app binds to port 3000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 3000