# Start the PeaPod software stack

services:
  peapodos:
    build:
      context: .
      dockerfile: Dockerfile.sim
    restart: always
    networks:
      - network
    stdin_open: true
    tty: true
    # command: ["yarn", "start"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html
    depends_on:
      - peapodos
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge