services:
  peapodos:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: always
    networks:
      - network
    stdin_open: true
    tty: true
    privileged: true
    # command: ["yarn", "dev"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html
    depends_on:
      - peapodos
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge